#!/usr/bin/bash

# Task:
# Write a script that converts a number from base 2 to base 10
# The number in base 2 is stored in the enviroment variable BINARY
# The script should display the number in base 10, followed by a new lane 

echo "$((2#$BINARY))"
